# Spellman Genes Validation

In [1]:
# Preamble, notebook setup and imports

%load_ext autoreload
%autoreload 2
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from src.config import load_combined_yl_vst_gene_expression_config

config = load_combined_yl_vst_gene_expression_config()

In [5]:
config.wt2_df

,0,10,20,30,40,50,60,70,80,90,100,120,130,140
orf_name,,,,,,,,,,,,,,
YAL068C,4.628603,4.650656,4.581064,4.267055,4.746247,4.267055,4.267055,4.629641,4.606230,4.267055,4.267055,4.578109,4.267055,4.267055
YAL067W-A,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055
YAL067C,8.699210,7.579643,8.004704,9.637574,9.600926,7.888115,7.196062,7.074505,6.865144,7.211349,7.038631,7.456671,7.354245,7.376803
YAL065C,5.209290,4.807974,4.710263,4.267055,4.606670,4.267055,4.267055,4.710551,4.851865,4.714847,4.267055,4.706108,4.570501,4.267055
YAL064W-B,5.701800,5.782681,5.949839,5.672654,5.791721,5.553199,5.617553,5.304455,5.821188,5.785532,5.691474,5.862783,5.827055,5.931531
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YPR200C,6.594912,6.711512,6.541217,6.466261,6.614168,6.541776,6.532153,6.429005,6.491524,6.385850,6.439477,6.447425,6.786357,6.658593
YPR201W,6.556583,6.876601,6.694993,6.990395,6.724441,6.729997,7.062747,6.562078,6.751741,6.715591,6.742779,6.622613,6.763110,6.504748
YPR202W,5.777234,6.038460,5.949839,5.443400,5.692170,5.986972,6.196960,6.385185,6.045158,5.698711,5.959244,5.887530,6.029427,6.014381
YPR203W,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055,4.267055
YPR204W,4.267055,5.027679,4.963797,5.008775,4.606670,4.588756,4.267055,4.629641,4.851865,4.970920,4.868124,4.578109,4.695408,4.779151

In [4]:
config.wt1_df

,0,20,30,40,50,60,70,80,90,100,110,120,130,140,150
orf_name,,,,,,,,,,,,,,,
YAL068C,4.035878,3.972461,3.585061,4.015432,4.004791,3.585061,3.585061,3.585061,3.585061,3.585061,3.943633,3.585061,3.585061,3.984531,3.970712
YAL067W-A,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061
YAL067C,8.384900,7.279818,8.736862,9.567278,8.433882,7.463686,7.187444,6.865723,7.113952,7.252361,7.211565,7.696468,7.817629,7.624664,7.385461
YAL065C,4.577539,4.252118,4.319898,4.015432,4.176593,4.323892,3.585061,3.585061,3.585061,4.479073,3.943633,4.230027,3.973553,4.148221,3.585061
YAL064W-B,5.627670,5.717082,5.343523,5.268900,5.394373,5.543765,5.624222,5.370802,5.492315,4.941777,5.555179,5.579397,5.532279,5.315841,5.429221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YPR200C,7.091267,6.899972,6.998422,6.764849,6.507118,6.559437,6.395874,6.477820,6.502191,6.491224,6.407670,6.579793,6.749337,6.565411,6.659330
YPR201W,6.959354,6.878564,6.596110,6.928381,6.692425,6.303943,6.433355,6.351937,6.571741,6.771816,6.938745,6.598354,6.676136,6.621609,6.899814
YPR202W,5.429854,5.766505,5.343523,5.435183,5.355564,5.646071,5.897336,6.082407,5.492315,6.013277,5.819514,5.860547,6.035182,6.150800,5.938654
YPR203W,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061,3.585061
YPR204W,4.035878,4.592513,4.012357,4.191483,4.176593,4.014713,4.440558,4.519606,4.198294,3.989973,3.943633,4.489892,4.132837,4.148221,3.970712